<a href="https://colab.research.google.com/github/ksb7762-k/Codeit/blob/main/numpy%EB%A1%9C_%ED%96%89%EB%A0%AC_%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np

# numpy로 행렬 만들기

In [17]:
A = np.array([
    [1, -1, 2],
    [3, 2, 2],
    [4, 1, 2],
    [7, 5, 6]
])

A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2],
       [ 7,  5,  6]])

In [18]:
B = np.array([
    [0, 1],
    [-1, 3],
    [5, 2]
])

B

array([[ 0,  1],
       [-1,  3],
       [ 5,  2]])

In [19]:
C = np.random.rand(3, 5)

C

array([[0.11065765, 0.21348118, 0.12250303, 0.74469926, 0.0585266 ],
       [0.20532144, 0.01964678, 0.32393371, 0.62687982, 0.70256664],
       [0.03039288, 0.72060634, 0.40941906, 0.72031874, 0.24991577]])

In [20]:
D = np.zeros((2, 4))

D

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# 행렬에서 원소를 받아오기

In [21]:
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2],
       [ 7,  5,  6]])

In [22]:
A[0][2] # 파이썬은 0부터 셈

np.int64(2)

# numpy로 요소별 곱하기 하기

In [23]:
import numpy as np

In [24]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [0, 1, 2],
    [2, 0, 1],
    [1, 2, 0]
])

In [25]:
A * B

array([[ 0,  2,  6],
       [ 8,  0,  6],
       [ 7, 16,  0]])

# numpy로 행렬 연산하기

In [26]:
A = np.array([
    [1, -1, 2],
    [3, 2, 2],
    [4, 1, 2]
])

B = np.random.rand(3, 3)

In [27]:
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2]])

In [28]:
B

array([[0.83908614, 0.7699381 , 0.79426484],
       [0.39253277, 0.36005269, 0.47184146],
       [0.09263217, 0.3929973 , 0.63315188]])

In [29]:
A + B

array([[ 1.83908614, -0.2300619 ,  2.79426484],
       [ 3.39253277,  2.36005269,  2.47184146],
       [ 4.09263217,  1.3929973 ,  2.63315188]])

In [30]:
5 * A  # 스칼라 곱

array([[ 5, -5, 10],
       [15, 10, 10],
       [20,  5, 10]])

In [31]:
np.dot(A, B) # 행렬과 행렬 곱하기

array([[0.63181772, 1.19588001, 1.58872714],
       [3.48758831, 3.81591428, 4.59278121],
       [3.93414169, 4.22579969, 4.91520459]])

In [32]:
A @ B

array([[0.63181772, 1.19588001, 1.58872714],
       [3.48758831, 3.81591428, 4.59278121],
       [3.93414169, 4.22579969, 4.91520459]])

In [33]:
A * B

array([[ 0.83908614, -0.7699381 ,  1.58852968],
       [ 1.1775983 ,  0.72010538,  0.94368293],
       [ 0.37052869,  0.3929973 ,  1.26630376]])

In [34]:
A @ B + (A + 2 * B)

array([[3.30999001, 1.73575621, 5.17725682],
       [7.27265384, 6.53601966, 7.53646414],
       [8.11940603, 6.01179429, 8.18150835]])

### 실습설명
이번 과제에서는 numpy를 사용해서 행렬 연산을 해보겠습니다. 지금 템플릿에는 행렬 4개, 각각 A,B,C,D의 행렬이 정의되어 있는데요. 이 행렬들을 이용해서 다음과 아래 행렬 연산을 해보세요.

2A × -B × (3C + D)


In [35]:
A = np.array([
    [1, -1, 2],
    [3, 2, 2]
])

B = np.array([
    [0, 1],
    [-1, 1],
    [5, 2]
])

C = np.array([
    [2, -1],
    [-3, 3]
])

D = np.array([
    [-5, 1],
    [2, 0]
])

In [36]:
result = 2 * A @ ((-1) * B) @ (3 * C + D)

result

array([[  34,  -28],
       [ 110, -130]])

## numpy로 전치, 단위, 역행렬 사용하기

In [37]:
A = np.array([
    [1, -1, 2],
    [3, 2, 2],
    [4, 1, 2]
])

In [38]:
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2]])

In [42]:
A_transpose = np.transpose(A)
A_transpose

array([[ 1,  3,  4],
       [-1,  2,  1],
       [ 2,  2,  2]])

더 쉬운 방법

In [43]:
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2]])

In [44]:
A_transpose = A.T
A_transpose

array([[ 1,  3,  4],
       [-1,  2,  1],
       [ 2,  2,  2]])

In [46]:
I = np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
A @ I

array([[ 1., -1.,  2.],
       [ 3.,  2.,  2.],
       [ 4.,  1.,  2.]])

In [50]:
A_inverse = np.linalg.pinv(A)
A_inverse

array([[-0.2, -0.4,  0.6],
       [-0.2,  0.6, -0.4],
       [ 0.5,  0.5, -0.5]])

In [51]:
A @ A_inverse

array([[ 1.00000000e+00,  5.55111512e-16, -8.88178420e-16],
       [ 0.00000000e+00,  1.00000000e+00, -8.88178420e-16],
       [ 0.00000000e+00,  3.33066907e-16,  1.00000000e+00]])

컴퓨터가 소수형을 다룰 때 완벽하게 표현하기 어려움. 그래서 소수형을 사용할 때 약간의 오차가 생길 수 밖에 없음