# 01. NumPy란? (Numerical Python: 수치적인 연산에 최적화된 파이썬 도구) 

# 02. NumPy와 array 

In [3]:
import numpy as np

In [4]:
array1 = np.array([1,3,5,6,7,9])
array1

array([1, 3, 5, 6, 7, 9])

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(4, 17, 3)

array([ 4,  7, 10, 13, 16])

In [9]:
type(array1)

numpy.ndarray

In [10]:
array2 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
array1.size

6

In [12]:
array2.size

12

In [13]:
array2.shape

(3, 4)

In [14]:
array1.shape

(6,)

# 03. 인덱싱과 슬라이싱: 1차원 array 

In [16]:
gdp_array = np.array([6610, 7637, 8127, 8885, 10385, 12565, 13403, 12398, 8282, 10672]) 

In [17]:
gdp_array[0]

6610

In [18]:
gdp_array[2]

8127

In [19]:
gdp_array[-1]

10672

In [20]:
gdp_array[-2]

8282

In [21]:
gdp_array[[1,3,4]]

array([ 7637,  8885, 10385])

In [22]:
array1 = np.array([2, 1, 3, 5])
gdp_array[array1]

array([ 8127,  7637,  8885, 12565])

In [23]:
gdp_array[2:6]

array([ 8127,  8885, 10385, 12565])

In [24]:
gdp_array[:6]

array([ 6610,  7637,  8127,  8885, 10385, 12565])

In [25]:
gdp_array[5:]

array([12565, 13403, 12398,  8282, 10672])

In [26]:
gdp_array[1:8:3]

array([ 7637, 10385, 12398])

# 04. (실습) 비트코인 가격 정보 탐색하기 1

### 실습 설명 
#### bitcoin_array에는 비트코인 투자 열풍이 불었던 2017년의 월별 비트코인 가격이 들어있습니다. 여기서 3분기(7월~9월)의 비트코인 가격만 가져와 보세요.

In [29]:
import numpy as np

bitcoin_array = np.array([970, 1180, 1072, 1348, 2286, 2481,
                          2875, 4703, 4339, 6468, 10234, 14156])

bitcoin_array[6:9]

array([2875, 4703, 4339])

# 05. 인덱싱과 슬라이싱 : 2차원 array 

In [31]:
gdp_array = np.array([
    [12257, 11561, 13165, 14673, 16496, 19403],  # 대한민국
    [39169, 34406, 32821, 35387, 38299, 37813],  # 일본
    [959, 1053, 1149, 1289, 1509, 1753],         # 중국
    [36335, 37133, 38023, 39496, 41713, 44115]   # 미국
])
gdp_array

array([[12257, 11561, 13165, 14673, 16496, 19403],
       [39169, 34406, 32821, 35387, 38299, 37813],
       [  959,  1053,  1149,  1289,  1509,  1753],
       [36335, 37133, 38023, 39496, 41713, 44115]])

In [32]:
gdp_array[1]

array([39169, 34406, 32821, 35387, 38299, 37813])

In [33]:
gdp_array[1][3]

35387

In [34]:
gdp_array[1:3, 2:5]

array([[32821, 35387, 38299],
       [ 1149,  1289,  1509]])

In [35]:
gdp_array[1:3, 2:]

array([[32821, 35387, 38299, 37813],
       [ 1149,  1289,  1509,  1753]])

In [36]:
gdp_array[:3, 2:5]

array([[13165, 14673, 16496],
       [32821, 35387, 38299],
       [ 1149,  1289,  1509]])

In [37]:
gdp_array[:, 2:5]

array([[13165, 14673, 16496],
       [32821, 35387, 38299],
       [ 1149,  1289,  1509],
       [38023, 39496, 41713]])

In [38]:
gdp_array[1:3, :]

array([[39169, 34406, 32821, 35387, 38299, 37813],
       [  959,  1053,  1149,  1289,  1509,  1753]])

# 06. 비트코인 가격 정보 탐색하기 2 

### 실습 설명
#### 이번에 실습에서 살펴볼 bitcoin_array는 2017년 월별 비트코인 가격과 거래량 정보가 들어 있는 2차원 array입니다. 첫 번째 로우에는 가격 정보, 두 번째 로우에는 거래량(천만 기준) 정보가 들어 있죠. 여기서 7월의 비트코인 거래량 정보만 가져와 보세요!

In [41]:
import numpy as np

bitcoin_array = np.array([[970, 1180, 1072, 1348, 2286, 2481,
						   2875, 4703, 4339, 6468, 10234, 14156],
						  [514, 428, 1087, 976, 3426, 4448,
						   3262, 6355, 5570, 5801, 14074, 41034]])

bitcoin_array[1, 6]

3262

# 07. 불린 인덱싱 

In [43]:
import numpy as np 

In [44]:
gdp_array = np.array([6610, 7637, 8127, 8885, 10385, 12565, 13403, 12398, 8282, 10672])

In [45]:
gdp_array > 10000

array([False, False, False, False,  True,  True,  True,  True, False,
        True])

In [46]:
mask = gdp_array > 10000
gdp_array[mask]

array([10385, 12565, 13403, 12398, 10672])

In [47]:
gdp_array[gdp_array > 10000]

array([10385, 12565, 13403, 12398, 10672])

In [48]:
gdp_array > 10000

array([False, False, False, False,  True,  True,  True,  True, False,
        True])

In [49]:
gdp_array < 8000

array([ True,  True, False, False, False, False, False, False, False,
       False])

In [50]:
gdp_array[(gdp_array > 10000) | (gdp_array < 8000)]

array([ 6610,  7637, 10385, 12565, 13403, 12398, 10672])

In [51]:
(gdp_array <= 10000) & (gdp_array >= 8000)

array([False, False,  True,  True, False, False, False, False,  True,
       False])

In [52]:
gdp_array[(gdp_array <= 10000) & (gdp_array >= 8000)]

array([8127, 8885, 8282])

# 08. 짝수만 추출하기 

### 실습 설명
#### 1부터 100까지 숫자가 들어 있는 numbers_array에서 짝수에 해당하는 숫자들만 뽑아 보세요!

In [55]:
import numpy as np

numbers_array = np.arange(1, 101)

numbers_array % 2 == 0

numbers_array[numbers_array % 2 == 0]

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

# 09. NumPy 기본 연산 

In [57]:
gdp_korea_array = np.array([12257, 11561, 13165, 14673, 16496, 19403])

In [58]:
gdp_korea_array.mean()

14592.5

In [59]:
gdp_korea_array.sum()

87555

In [60]:
gdp_korea_array.min()

11561

In [61]:
gdp_korea_array.max()

19403

In [62]:
gdp_korea_array * 1200

array([14708400, 13873200, 15798000, 17607600, 19795200, 23283600])

In [63]:
gdp_korea_array

array([12257, 11561, 13165, 14673, 16496, 19403])

In [64]:
gdp_korea_array = gdp_korea_array * 1200
gdp_korea_array

array([14708400, 13873200, 15798000, 17607600, 19795200, 23283600])

In [124]:
gdp_korea_array = gdp_korea_array / 1200
gdp_korea_array

array([12257., 11561., 13165., 14673., 16496., 19403.])

In [126]:
gdp_us_array = np.array([36335, 37133, 38023, 39496, 41713, 44115]) 

In [128]:
gdp_us_array - gdp_korea_array 

array([24078., 25572., 24858., 24823., 25217., 24712.])

In [130]:
gdp_us_array / gdp_korea_array 

array([2.96442849, 3.21191938, 2.88818838, 2.69174675, 2.52867362,
       2.27361748])

# 10. 쇼핑몰 매출액 계산하기 

### 실습 설명 
#### 소원이는 부업으로 인터넷 쇼핑몰 운영을 시작했습니다. 가격은 price_array, 판매 수량은 quantity_array에 저장되어 있는데요. 치마, 티셔츠, 원피스, 스웨터, 코트, 청바지, 신발 순서대로 정보가 들어 있다고 합니다. 각 상품별 매출액을 한번 계산해 볼까요? 실습 코드를 실행하면 아래와 같은 형태의 결과물이 출력되어야 합니다.

In [136]:
import numpy as np

price_array = np.array([30000, 25000, 40000, 60000, 95000, 35000, 50000])
quantity_array = np.array([10, 13, 7, 20, 6, 19, 9])

price_array * quantity_array 

array([ 300000,  325000,  280000, 1200000,  570000,  665000,  450000])